name: resumestudio
description: A Resume Builder cross-platfom flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_ui:
    path: ./packages/app_ui
  bloc: ^8.1.2
  flexilayout:
    path: ./packages/flexilayout
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
