name: app_ui
description: A package to manage app comon widgets
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  mockingjay: ^0.5.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
